### PR TITLE
comprised of the commits listed below

### PR DESCRIPTION
**Pull request by cborys19**
may mess with the .idea files. no idea what happened.

### CODE REVIEW

**Review by sepfeiffer — CHANGES_REQUESTED** [review]
trying to remove idea files

**Review by cborys19 — COMMENTED** [review]
deleted .idea files

**Review by sepfeiffer — CHANGES_REQUESTED** [review]
vcs.xml should be removed

**Comment by cborys19** [comment]
i already deleted vcs.xml in a commit. i can't see it anywhere.

**Review by sepfeiffer — APPROVED** [review]
idea files were removed, rest of code looks good -sam

**Comment by ddfn** [comment]
Hi Sam, just had a chance to review the changes too. Just wanted to note that I like what you did with the hamburger button. the menu looks great too

**Pull request merged**
